---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace}}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ .clustername}}
  namespace: {{ .namespace}}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .podcidr | quote }}  # CIDR block used by Calico
    services:
      cidrBlocks:
      - {{ .servicecidr | quote }} # CIDR block used by Calico
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: {{ .clustername}}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: {{ .clustername}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: {{ .clustername}}
  namespace: {{ .namespace}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: {{ .clustername}}
  namespace: {{ .namespace}}
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: {{ .clustername}}
  namespace: {{ .namespace}}
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachineTemplate
    name: {{ .clustername}}
  kubeadmConfigSpec:
    clusterConfiguration:
      kubernetesVersion: {{ .kubernetesversion}}
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  replicas: ${ CONTROL_PLANE_MACHINE_COUNT }
  version: {{ .kubernetesversion}}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: {{ .namespace}}-md-0
  namespace: {{ .namespace}}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /var/run/containerd/containerd.sock
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .clustername}}
  name: {{ .namespace}}-md-0
  namespace: {{ .namespace}}
spec:
  clusterName: {{ .clustername}}
  replicas: {{ .kubernetesmachinecount}}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .clustername}}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .clustername}}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: {{ .namespace}}-md-0
      clusterName: {{ .clustername}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: DockerMachineTemplate
        name: {{ .clustername}}
      version: {{ .kubernetesversion}}
    