---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | quote }}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ .clustername | quote }}
  namespace: {{ .namespace | quote }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - '${ POD_CIDR}'  # CIDR block used by Calico
    services:
      cidrBlocks:
      - '${ SERVICE_CIDR }' # CIDR block used by Calico
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: {{ .clustername | quote }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: {{ .clustername | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: {{ .clustername | quote }}
  namespace: {{ .namespace | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: {{ .clustername | quote }}
  namespace: {{ .namespace | quote }}
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: {{ .clustername | quote }}
  namespace: {{ .namespace | quote }}
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachineTemplate
    name: {{ .clustername | quote }}
  kubeadmConfigSpec:
    clusterConfiguration:
      kubernetesVersion: '${ KUBERNETES_VERSION }'
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  replicas: ${ CONTROL_PLANE_MACHINE_COUNT }
  version: '${ KUBERNETES_VERSION }'
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: '${ CLUSTER_NAME }-md-0'
  namespace: {{ .namespace | quote }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /var/run/containerd/containerd.sock
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .clustername | quote }}
  name: '${ CLUSTER_NAME }-md-0'
  namespace: {{ .namespace | quote }}
spec:
  clusterName: {{ .clustername | quote }}
  replicas: ${ WORKER_MACHINE_COUNT }
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .clustername | quote }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .clustername | quote }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: '${ CLUSTER_NAME }-md-0'
      clusterName: {{ .clustername | quote }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: DockerMachineTemplate
        name: {{ .clustername | quote }}
      version: '${ KUBERNETES_VERSION }'
    